#! /usr/bin/python

import sys
sys.path.append("../msconfig")
import CGIUtils
sys.path.append("../var")
from Config import MAPSERVER_EXE

MAPFILE = '../msconfig/lsf-ndvi.map'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERVER_EXE)