#! /usr/bin/python

import sys
sys.path.append("../msconfig")
import CGIUtils

MAPFILE = '../msconfig/rlayers.map'

MAPSERV = '../cgi-bin/mapserv641.exe'

CGIUtils.mapserv_inject_mapfile(MAPFILE, MAPSERV)
